### ISSUE TITLE
NeoCompleteIncludeMakeCache command

### ISSUE THREAD

**Issue by petobens** [Shougo/neoinclude.vim#1]
When the include source was part of neocomplete I could use the command `:NeoCompleteIncludeMakeCache` to make cache. How do I this now? Thanks in advance.

I want to be able to use the following mapping again:

``` vim
nnoremap <silent> <Leader>te :NeoCompleteIncludeMakeCache<CR>:Unite
            \ tag/include<CR>
```

**Comment by Shougo** [comment]
Implemented.

**Comment by petobens** [comment]
Awesome. Thank you!!
