### ISSUE TITLE
HTML script src="" error

### ISSUE THREAD

**Issue by eugen0329** [Shougo/neoinclude.vim#10]
There are several errors with html script tag.
When I start to edit at the cursor_position_1, expepected that the deoplete will be triggered neoinclude source, but there are only omni pattens. Nevertheless, inside of the tag (at the cursor_position_1) I don't find a single omni (although everthing works well if I try to complete manually with <C-x><C-o>)

Test file content:
<script src="{cursor_position_1}">
&nbsp;&nbsp;&nbsp;&nbsp;{cursor_position_2}
</script>

Neovim config file content:
set runtimepath+=~/.vim/bundle/deoplete.nvim/
set runtimepath+=~/.vim/bundle/neoinclude.vim/
filetype plugin indent on

**Comment by Shougo** [comment]
For 2nd problem:  Please install context_filetype.vim.

https://github.com/Shougo/context_filetype.vim

**Comment by Shougo** [comment]
For 1st problem: Please update deoplete and neoinclude.

**Comment by eugen0329** [comment]
2nd issue is fixed, but it's still problems with neoinclude: now there is no omni suggestions, but also there is no file/include candidates.

**Comment by Shougo** [comment]
Reproduced.  I will fix it later.

**Comment by Shougo** [comment]
Fixed.

**Comment by eugen0329** [comment]
Cool! Works great. Thanks for you attention:)
By the way, it might be a good idea to implement the same feature for stylesheet link, don't you think?
<link rel="stylesheet" type="text/css" href="{cursor}">

**Comment by eugen0329** [comment]
Hmm, it's still slightly weird behaviour there: if src is blank ( src=""{cursor} ), and if I enter insert mode after the closing quote, file_include candidates will be shown. Problem is not fatal, but it seems it is not difficult to fix with more appropriate regexp.

But on the other hand, there is one more problem - when I typing in any position inside of the opening script tag (inserting "type=" attribute, for instance), it's still omni candidates. This is strange and sometimes vim can considerably hang.

**Comment by Shougo** [comment]
> Cool! Works great. Thanks for you attention:)
> By the way, it might be a good idea to implement the same feature for stylesheet link, don't you think?
> 
> Hmm, it's still slightly weird behaviour there: if src is blank ( src=""{cursor} ), and if I enter insert mode after the closing quote, file_include candidates will be shown. Problem is not fatal, but it seems it is not difficult to fix with more appropriate regexp.

Fixed both.

> But on the other hand, there is one more problem - when I typing in any position inside of the opening script tag (inserting "type=" attribute, for instance), it's still omni candidates. This is strange and sometimes vim can considerably hang.

It is htmlcomplete problem.  I cannot fix it.
You can report the behavior to the maintainer.

**Comment by eugen0329** [comment]
Thanks for you responce:)
