### ISSUE TITLE
how to get this working with go?

### ISSUE THREAD

**Issue by nhooyr** [Shougo/neoinclude.vim#11]
I managed to get the file include working with a pattern but obviously that makes no sense with go. Its also only recognizes the single line version of the import statement, e.g.

``` go
import "io/ioutil"
```

But it can't recognize

``` go
import (
    "io/ioutil"
)
```

I can add a vim function or even an external program to get a list of all the import paths but how would I plug that into this plugin?

**Comment by Shougo** [comment]
You should install vim-go or deoplete go plugin.
It supports import completion.

**Comment by nhooyr** [comment]
Its still a in progress for deoplete-go and for vim-go you have to run a command. It'd be easier to have proper autocomplete for imports. But I guess wait until deoplete-go has it.
