### ISSUE TITLE
Wrong css/scss url() completion

### ISSUE THREAD

**Issue by eugen0329** [Shougo/neoinclude.vim#13]
According to w3: 
Partial URLs are interpreted relative to the source of the style sheet, not relative to the document.

Source: https://www.w3.org/TR/REC-CSS1/#url

So if I have a css file in css/ and images in img/, proper completion result must be:
background-image: url(../img/bg.png);

**Comment by Shougo** [comment]
It is not neoinclude work.
Please report it in the csscomplete author.
