### ISSUE TITLE
How to g:neoinclude#paths

### ISSUE THREAD

**Issue by astavonin** [Shougo/neoinclude.vim#16]
As neoinclude user I'd like to add additional paths to g:neoinclude#paths. Unfortunately, I didn't find an API call to do it. Is it possible to add such API call or include an example into the documentation.

**Comment by Shougo** [comment]
What is the API?
I don't understand it.
I have not ESP skills.

**Comment by astavonin** [comment]
While you are not Vim-script Guru, there is no way to extend paths-list. The paths-list is a sort of dictionary with a list inside and it’s not trivial to add something inside it without: a) a function which made for end user; b) an example how to do it.

**Comment by Shougo** [comment]
OK.  But I don't want to add the API.
neoinclude uses helper function though.

``` vim
  call neoinclude#util#set_default_dictionary(
        \ 'g:neoinclude#paths', 'cpp',
        \ 'value')
```

Pull request is wellcome.
