### ISSUE TITLE
Using includeexpr to cut-off .js extension when importing files

### ISSUE THREAD

**Issue by FuzzOli87** [Shougo/neoinclude.vim#18]
Hello,

I saw your comment on the deoplete.nvim thread [https://github.com/Shougo/deoplete.nvim/issues/300](url) 

I tried multiple ways to make this work but frankly, I'm quite unsure of how to use the options in this plugin cut off the extension when importing '.js' files. 

I tried:

```
if !exists('g:neoinclude#reverse_exprs')
  let g:neoinclude#reverse_exprs = {}
endif
let g:neoinclude#reverse_exprs.js =
      \ 'fnamemodify(substitute(v:fname, "\.js$", "", ""), ":r")'
```

I also tried setting the option directly:
`set includeexpr= 'fnamemodify(substitutev:fname,'\\.js', '', ''))'`

But these were just shots in the dark. I would appreciate your guidance in this.

**Comment by Shougo** [comment]
``` vim
let g:neoinclude#reverse_exprs.javascript =
```

It must be `javascript`.

**Comment by Shougo** [comment]
> I also tried setting the option directly:

You should study `:set` and `:setlocal` features.

**Comment by dsifford** [comment]
Hey @Shougo, thanks for the feedback here already. I appreciate your patience.

Quick follow up question here: Are you aware of a conflict between this plugin and `LanguageClient-neovim`? It seems like I can get this to work in all filetypes that do not have a running language server.

Any tips for remediating this?

**Comment by Shougo** [comment]
I don't know about the problem.

neoinclude is just library.
It works with and without LanguageClient-neovim.

> It seems like I can get this to work in all filetypes that do not have a running language server.

I don't understand `to work` means.

**Comment by dsifford** [comment]
Without languageclient, I can cut off file extensions without any problem using the method described above. 

With languageclient, I can not cut off file extensions.

**Comment by Shougo** [comment]
I don't know why.
