### ISSUE TITLE
Completion from include files is not automatically triggered

### ISSUE THREAD

**Issue by tcbbd** [Shougo/neoinclude.vim#28]
The tag completion source is only initialized when the `on_event` of deoplete source is called. So if I added some new include files, I must save the file to get completion from those files. This is a bit annoying.

Even worse, when I first open a file (e.g. `nvim foo.c`), I can't get the neoinclude completions, I must first enter insert mode then exit (to activate deoplete & neoinclude), and then save the file (with no modifications yet) to make the neoinclude completions work, this is very strange. I would expect I can get neoinclude completions without any special operation, instead of activating (initializing) it manually.

Maybe this issue should be resolved by patching deoplete code (I'm not sure), but I think it's better to report it here ^_^

**Comment by Shougo** [comment]
> The tag completion source is only initialized when the on_event of deoplete source is called. So if I added some new include files, I must save the file to get completion from those files. This is a bit annoying.

This is neoinclude.vim features instead of deoplete.

> Even worse, when I first open a file (e.g. nvim foo.c), I can't get the neoinclude completions, I must first enter insert mode then exit (to activate deoplete & neoinclude), and then save the file (with no modifications yet) to make the neoinclude completions work, this is very strange

This is deoplete tag source issue instead of neoinclude.vim.
Closing.

**Comment by tcbbd** [comment]
> This is deoplete tag source issue instead of neoinclude.vim.
> Closing.

So I should open an issue for deoplete or this is the expected behavior?

**Comment by tcbbd** [comment]
If I make `on_event` called when `InsertEnter`, will it cause too much overhead? Will it accidentally break other sources?

**Comment by Shougo** [comment]
> So I should open an issue for deoplete or this is the expected behavior?

Please create new issue in deoplete.

> If I make on_event called when InsertEnter, will it cause too much overhead? Will it accidentally break other sources?

tag source should check the cache like dictionary source.
I will fix it.  So don't need to check it on InsertEnter.
