### ISSUE TITLE
get_include_files() always running when using NCM

### ISSUE THREAD

**Issue by ZeroKnight** [Shougo/neoinclude.vim#29]
### Clarification for the future
This issue was originally opened due to performance issues caused by my own ignorance. There was a legitimate bug in that when using [nvim-completion-manager](https://github.com/roxma/nvim-completion-manager), `get_include_files()` was being run all the time, instead of just on `#include` directives, which is what PR #30 fixes. The following is the original, misguided report.

## Original Report

I'm using neovim-completion-manager and getting very poor performance when using neoinclude; check out [this profile](https://ptpb.pw/42pW). Specifically:

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   11   9.991828   9.959356  neoinclude#file_include#get_include_files()
...
```

I'm unsure why, but neoinclude is executing this function no matter what I'm typing in a **cpp** buffer, even if it's not an `#include` directive. For example, when creating the above profile, this is all that I typed into an empty **cpp** buffer:

```cpp
int main()
{
  return 0;
}
```

The UI froze several times as I typed this, likely due to `get_include_files()` executing. Of course, this makes nvim entirely unusable. Is this normal? Shouldn't neoinclude only be executing when the line matches an `#include` directive? Even then the slow-down makes this unusable.

**Comment by Shougo** [comment]
This is nvim-completion-manager source problem.
I cannot support  it.

@jsfaint Please fix it.
The source should skip the completion if it is not `#include`.
`get_include_files()` is very slow.
https://github.com/Shougo/neoinclude.vim/pull/26

**Comment by Shougo** [comment]
`neoinclude#file_include#get_complete_position()` call is needed.

**Comment by Shougo** [comment]
I will remove the source if you cannot fix it...

**Comment by jsfaint** [comment]
@Shougo `neoinclude#file_include#get_complete_position()` is already called in ncm source
I skip the completion when `neoinclude#file_include#get_complete_position()` return `-1`.

Sorry for inconvenience.

@ZeroKnight Can you try this fix to check if it fix your issue?
Thanks

**Comment by ZeroKnight** [comment]
@jsfaint Yeah, that fixed it. It only runs that completer on `#include` lines now. It's still *very* slow to complete the list (why are there so many tag results? Shouldn't only header files be valid completions?), but it's at least done in the proper place now.

**Comment by jsfaint** [comment]
@ZeroKnight Maybe you need to check your vim config.
It works well on my side like always.
![nvim](https://user-images.githubusercontent.com/571829/30201603-f179e614-94ad-11e7-8e28-f790615040c7.gif)

**Comment by ZeroKnight** [comment]
@jsfaint I'm currently looking into that. I believe the reason it executes so slowly is because for some reason my completion list ends up with **26,000+ results**. Scrolling through it, it appears to have header files from projects all over my hard drive. What might be causing so many unrelated results to be included? I haven't configured neoinclude at all, so options are default.

**Comment by ZeroKnight** [comment]
Here's an example of the sheer magnitude of the number of candidates I'm getting.

![neoinclude_example](https://user-images.githubusercontent.com/719733/30203094-c73f6d74-9435-11e7-9188-14cf081568d7.gif)

**Comment by jsfaint** [comment]
What's the result of `:echo g:neoinclude#paths`?

**Comment by ZeroKnight** [comment]
> What's the result of `:echo g:neoinclude#paths`?

https://ptpb.pw/WCis

**Comment by ZeroKnight** [comment]
Oh I see, it uses `path` to populate that list. My `path` as set in my init.vim:

```
set path=.;include,/usr/include/**,./**,$PWD/**
```

That would make sense. I'll need to adjust this.

[EDIT]
Confirmed. Using a default `path` setting reduces the candidates to a mere 3,572 results. I'm going to fix my `path` setting now.

Thank you for pointing me in the right direction, @jsfaint.

**Comment by jsfaint** [comment]
@ZeroKnight :+1: Thanks for the bug report, I never notice it before.

**Comment by ZeroKnight** [comment]
Just for future clarity, I've adjusted the title of this issue and left a note in the original post.

Cheers 😃

**Comment by Shougo** [comment]
@jsfaint Thanks.

**Comment by jsfaint** [comment]
@Shougo Sorry for inconvenience
