### ISSUE TITLE
Candidates not shown when reusing tag source

### ISSUE THREAD

**Issue by petobens** [Shougo/neoinclude.vim#3]
Consider the following minimal vimrc:

``` vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/unite
set runtimepath+=$DOTVIM/bundle/neocomplete
set runtimepath+=$DOTVIM/bundle/neoinclude
set runtimepath+=$DOTVIM/bundle/unite-tag
set runtimepath+=$DOTVIM/bundle/vimproc
filetype plugin indent on

let g:neocomplete#enable_at_startup = 1
nnoremap <silent> ,te :NeoIncludeMakeCache<CR>:Unite
            \ tag/include<CR>
```

As in the GIF, open Gvim, edit the `vimrc_min` file and press `,te`. The unite buffer will display the candidates from the tag source. Now close the unite buffer with `q` and once again press `,te`. The unite buffer is now empty. I expect for it to show the candidates.

![blah](https://cloud.githubusercontent.com/assets/2583971/9469849/93505f34-4b1f-11e5-94ff-6deb7367c549.gif)

**Comment by Shougo** [comment]
I cannot reproduce the problem by following vimrc.

``` vim
set nocompatible

set runtimepath+=~/work/unite.vim/
set runtimepath+=~/work/neoinclude.vim/
set runtimepath+=~/work/unite-tag/
set runtimepath+=~/work/vimproc.vim/
filetype plugin indent on

nnoremap <silent> ,te :NeoIncludeMakeCache<CR>:Unite
            \ tag/include<CR>
```

Note: neocomplete is not needed for neoinclude/unite-tag.

**Comment by Shougo** [comment]
@petobens You should check `neoinclude#include#got_tag_files()` result.
And you can check `neoinclude#include#get_tag_files()` implementation.
I cannot fix the problem.  Because, I cannot reproduce it.
The source code is already opened.

**Comment by petobens** [comment]
Hi @Shougo. The first time I use the mapping, `neoinclude#include#get_tag_files()` returns `['C:/Users/Pedro/AppData/Local/Temp/VIC9106.tmp']` and the second time I use it (when the candidates are not shown) it returns `['C:/Users/Pedro/AppData/Local/Temp/VIF608D.tmp']`. In both cases the temp file is:

```
!_TAG_FILE_FORMAT   2   /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED   1   /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR    Universal Ctags Team    //
!_TAG_PROGRAM_NAME  Universal Ctags /Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL   https://ctags.io/   /official site/
!_TAG_PROGRAM_VERSION   Development //
$DOTVIM C:/OD/Users/Pedro/vimfiles/vimrc_min    /^let $DOTVIM = expand('$ONEDRIVE_HOME\/vimfiles')$/;"  kind:variable   line:4  language:Vim
$ONEDRIVE_HOME  C:/OD/Users/Pedro/vimfiles/vimrc_min    /^let $ONEDRIVE_HOME = expand('C:\/OD\/Users\/Pedro')$/;"   kind:variable   line:3  language:Vim
,te C:/OD/Users/Pedro/vimfiles/vimrc_min    /^nnoremap <silent> ,te :NeoIncludeMakeCache<CR>:Unite$/;"  kind:map    line:12 language:Vim
vimrc_min   C:/OD/Users/Pedro/vimfiles/vimrc_min    1;" kind:file   line:1  language:Vim

```

The temp file is therefore correctly created in both cases. 

I found out that the problem is, for some reason, related to the mapping: if I the second time I manually run `:NeoIncludeMakeCache` and then `:Unite tag/include` then the candidates are shown. On the other hand, if I use the `,te` mapping they are not shown:

![fooo](https://cloud.githubusercontent.com/assets/2583971/9495201/a87579b4-4be0-11e5-913b-765e55463cf0.gif)

Why doesn't the mapping work? (given the fact that  running the command manually does work)

**Comment by Shougo** [comment]
> Why doesn't the mapping work? (given the fact that running the command manually does work)

I don't know.
You should check `neoinclude#include#make_cache()` and `s:check_buffer()` implementation.
The source code is already opened.  And you can fix it.

**Comment by petobens** [comment]
Thanks @Shougo, I will check it.

**Comment by petobens** [comment]
@Shougo an ugly workaround is writing the mapping like this:

``` vim
nnoremap <silent> ,te :NeoIncludeMakeCache<CR>:sleep 3m<CR>:Unite
            \ tag/include<CR>
```

That way the mapping works just fine and candidates are correctly displayed. I don't know if it helps to find the source of the problem. I will investigate further.

**Comment by petobens** [comment]
I don't know the source of the problem, but since the above mapping works I'm closing.

**Comment by Shougo** [comment]
OK.  I get the problem.
I will fix it.

**Comment by petobens** [comment]
Hi @Shougo, after your recent commit I get the following error:

```
Error detected while processing function neoinclude#include#make_cache..<SNR>137_check_buffer..<SNR>137_initialize_include:
line   20:
E484: Can't open file C:/Users/Pedro/AppData/Local/Temp/VIoD477.tmp

```

**Comment by Shougo** [comment]
Please test the command in `s:initialize_include()` command.
It seems "ctags" command was failed.
You can check it.

**Comment by petobens** [comment]
Thank you! It is fixed now.
