### ISSUE TITLE
Sets local directory for files (haslocaldir) / misuse of `:lcd`

### ISSUE THREAD

**Issue by blueyed** [Shougo/neoinclude.vim#31]
There are two places where `:lcd` is used, and this causes `haslocaldir()` to become 1.

I think that `:lcd` should only be used if there is local working dir already, and otherwise `tcd`/`cd` should be used.

Then this also can be skipped if the `cwd` is the expected one already.

I am using the following in Neomake:
https://github.com/neomake/neomake/blob/0ec94d39a26dd624e939f774adb161d08d6d193e/autoload/neomake.vim#L1713-L1727

**Comment by blueyed** [comment]
Thanks!

1. Why is the `cd` necessary after all?
2. Should it also be done for nested includes then? https://github.com/Shougo/neoinclude.vim/blob/4b4b92b1424bb470eb7a3e23a8ec0b576f93a766/autoload/neoinclude/include.vim#L175

**Comment by Shougo** [comment]
> Why is the cd necessary after all?

Because, the include files may be local file in the directory.
Eg: C, C++

**Comment by blueyed** [comment]
Then it should be done for the nested files, too.
This means to move it to `s:get_include_files` maybe?!

**Comment by Shougo** [comment]
The PR is wellcome.
