### ISSUE TITLE
javascript require import support

### ISSUE THREAD

**Issue by plexigras** [Shougo/neoinclude.vim#35]
or maybe someone can tell me how to add `$(npm config get prefix)/lib/node_modules` and `$(npm prefix)/node_modules` as paths.

**Comment by Shougo** [comment]
`:help g:neoinclude#paths`

**Comment by plexigras** [comment]
can you tell me how because the help is not all that clear.

**Comment by Shougo** [comment]
`When there is not it, 'path' is used.	Refer to 'path' for the description form.`

If so, you should use path option.

**Comment by plexigras** [comment]
i cant get it to work and i still think it would be nice if neoinclude had javascript support by default?

**Comment by Shougo** [comment]
Pull request is wellcome.
I don't get the generic solution.

No magic.

**Comment by Shougo** [comment]
Open source solution:
You can fix it if you really need the feature.

**Comment by Shougo** [comment]
Hint:
You can add the support in the function.

https://github.com/Shougo/neoinclude.vim/blob/master/autoload/neoinclude.vim#L175
