### ISSUE TITLE
Can't complete path without quote(“  ‘）

### ISSUE THREAD

**Issue by kdurant** [Shougo/neoinclude.vim#36]
`vlog  ../Src/remote_update/`, can't  complete path 

`vlog  "../Src/remote_update/`, can  complete path

**Comment by Shougo** [comment]
I don't understand.
If you don't provide the installation to reproduce, I will close it.

**Comment by Shougo** [comment]
You can reproduce the problem with your provided information?

**Comment by kdurant** [comment]
1. open a buffer with neovim-qt
2. Enter `some ../`
3. can't display candidates from included path.

**Comment by Shougo** [comment]
It is not the reproduce instructions.
Please upload the minimal vimrc.
If not, I will close the issue.

**Comment by Shougo** [comment]
Other people can reproduce the problem with your instructions ?
I don't think so.

**Comment by Shougo** [comment]
Please read other issues like deoplete.
