### ISSUE TITLE
#include basics

### ISSUE THREAD

**Issue by chimeworld** [Shougo/neoinclude.vim#37]
How can I set this up to complete for things like iostream, iomanip, cmath, etc. in C++?

Specifically referring to these statements:

    #include <iostream>
    #include <iomanip>
    #include <cmath>

**Comment by Shougo** [comment]
Please read the documentation.

```
g:neoinclude#paths				*g:neoinclude#paths*
		It is the variable to enumerate path of the include file
		every file type.  When there is not it, 'path' is used.
		Refer to 'path' for the description form.  It is the
		dictionary of the character string that assumed file type a
		key.

		Default value is in "g:neoinclude#_paths".
```

You must set `path` option or `g:neoinclude#paths` variable.

**Comment by Shougo** [comment]
If you set the variable properly, `neoinclude#include#get_current_include_files()` works.

**Comment by chimeworld** [comment]
is this right?

`let g:neoinclude#paths = {'cpp': '/usr/local/include'}`

What if I wanted multiple paths for 'cpp'?

Also, I'm not sure what I'm supposed to do with `neoinclude#include#get_current_include_files()`.

**Comment by chimeworld** [comment]
^^ that only seems to work properly if I change it to `{'cpp': '/usr/local/include/c++/8.2.0'}` which doesn't seem ideal

**Comment by Shougo** [comment]
It is the right.
This is c++ path feature.  Not neoinclude issue

**Comment by zzdts** [comment]
@Shougo  could you give some example to config this plugin ?
I have configed like this `let g:neoinclude#paths = {"c":"~/work/viml/linc/include"}` but is doe's not work
`~/work/viml/linc/` is project root ,  when i into directory  "linc" and  edit c file with vim ,  deoplete can't give any  prompt message。
I get nothing at vim cmdline when i run `call neoinclude#include#get_current_include_files()`  cmd.

**Comment by Shougo** [comment]
> I get nothing at vim cmdline when i run `call neoinclude#include#get_current_include_files()` cmd.

It must be:
```vim
echo neoinclude#include#get_current_include_files() 
```

**Comment by Shougo** [comment]
> I have configed like this let g:neoinclude#paths = {"c":"~/work/viml/linc/include"} but is doe's not work

You must expand `~`.  neoinclude does not expand `~` automatically.

I think it is same with 'path' option behavior.

**Comment by zzdts** [comment]
used absolute path and run cmd  _echo neoinclude#include#get_current_include_files()_     
it return a  NULL  list . 
I used  this plugin in  [https://github.com/SpaceVim/SpaceVim](url)  ， is some thing wrong with SpaceVim ？

**Comment by Shougo** [comment]
Hm.  I will test it later.
But you don't upload the minimal vimrc and test project.

Please test neoinclude without SpaceVim.

**Comment by Shougo** [comment]
If not, I don't test and support for you.
I am not time to waste.

Note:  Please see my activity in github.
