### ISSUE TITLE
Huge list of include paths with clangx

### ISSUE THREAD

**Issue by mayjs** [Shougo/neoinclude.vim#39]
With `neoinclude` and `deoplete-clangx`, completion stops working after the first time for me.
After investigating what's happening, I noticed the huge amount of arguments `deoplete-clangx` was using on the second run.

It's about 550 single `-I` parameters and seems to include every single library on my system. This can't be how it's supposed to work, can it? I had to disable this plugin since clangx was basically unusable.

**Comment by Shougo** [comment]
You can disable the auto detection by:

```vim
let g:neoinclude#paths = {'cpp': ''}
```
