### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by soonsolidchentuo** [Shougo/neoinclude.vim#42]
Hello, can I use this tool to develop kernel code?

I want to specify a directory. For example, in kernel/include, all function declarations will be automatically prompted when I use vim.

neoinclude.vim Can you help me achieve this function? How to set it?

Thank you from the bottom of my heart

**Comment by Shougo** [comment]
Have you read the documentation???

`:help g:neoinclude#paths`

You should study `:help 'path'` in the first.

**Comment by Shougo** [comment]
This plugin is not easy to use.  Because this is just helper plugin.
But you are not beginner of programmer as kernel developer.
So you can read the code and other issues and can understand it.

I have not much time to explain it to you.
