### ISSUE TITLE
Feature request: show (and filter) candidates by kind

### ISSUE THREAD

**Issue by petobens** [Shougo/neoinclude.vim#5]
Consider the following minimal vimrc:

``` vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/unite
set runtimepath+=$DOTVIM/bundle/neoinclude
set runtimepath+=$DOTVIM/bundle/unite-tag
set runtimepath+=$DOTVIM/bundle/vimproc
set runtimepath+=$DOTVIM/bundle/tagbar/
filetype plugin indent on

nnoremap <silent> ,te :NeoIncludeMakeCache<CR>:sleep 3m<CR>:Unite
            \ tag/include<CR>
```

Now open the `Gvim`, edit that `vimrc_min` file and press `,te`. Candidates will be correctly displayed but for each candidate there is no information of its `kind`. On the other hand the `tagbar` plugin shows this useful info (whether a candidate is `variable` or a `map` or a `function`, etc). So I was wondering if it is possible to show the `kind` of each candidate in the unite buffer and to allow to filter by `kind`. I think this might be a nice feature to have.
Thanks in advance!

![blahh](https://cloud.githubusercontent.com/assets/2583971/9547647/14238588-4d72-11e5-8877-02a7507db75a.gif)

**Comment by Shougo** [comment]
Note: It is not neoinclude issue!

Implement this feature in unite-tag.

> So I was wondering if it is possible to show the kind of each candidate in the unite buffer and to allow to filter by kind. I think this might be a nice feature to have.

If you want to filter by kind, you must use "converter_abbr_word".
