### ISSUE TITLE
Generate tags for files in current directory

### ISSUE THREAD

**Issue by petobens** [Shougo/neoinclude.vim#6]
Suppose I have the following `m` files in the same directory:

i) `bar.m`:

``` matlab
function y = bar(x)
    y = x + 2;
end
```

 ii) `foo.m`

``` matlab
disp(bar(2))
```

(i.e from the file `foo.m` I'm calling a function `bar()` defined in the file `bar.m`).

Now, using [universal-ctags](https://github.com/universal-ctags/ctags) If run `!ctags -R *.m` from the file `foo.m`, the following tag file is generated:

```
!_TAG_FILE_FORMAT   2   /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED   1   /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR    Universal Ctags Team    //
!_TAG_PROGRAM_NAME  Universal Ctags /Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL   https://ctags.io/   /official site/
!_TAG_PROGRAM_VERSION   Development //
bar bar.m   /^function y = bar(x)$/;"   f
```

which then allows me to place the cursor in `bar(2)` (in `foo.m`) and press `C-]` to jump to the `bar()` function definition in `bar.m`. 

I'm trying to replicate this behavior using `neoinclude` and `unite-tag`. However when I use the mapping (without running `!ctags -R *.m`):

``` vim
 nnoremap <buffer> <silent> <C-]> :NeoIncludeMakeCache<CR>
                \ :UniteWithCursorWord -immediately -sync tag/include<CR>

```

nothing happens.

I think I found the problem: if from `foo.m` I run `:NeoIncludeMakeCache` and  then `:Unite tag/include` I get an empty buffer.
So this means that no tags are generated for `bar.m`.  However I expect neoinclude to generate tags for `bar.m` since according to the docs:

> g:neoinclude#paths 
>         It is the variable to enumerate path of the include file
>         every file type.  When there is not it, 'path' is used.
>         Refer to 'path' for the description form.  It is the
>         dictionary of the character string that assumed file type a
>         key.

and I run `set path?` I get `path=.,,` which means that the current directory is included (however `echo g:neoinclude#_paths` returns `{}` . 

Btw, here is a minimal vimrc and Gif showing the problem:

``` vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/unite
set runtimepath+=$DOTVIM/bundle/neoinclude
set runtimepath+=$DOTVIM/bundle/unite-tag
set runtimepath+=$DOTVIM/bundle/vimproc
filetype plugin indent on
```

![gif](https://cloud.githubusercontent.com/assets/2583971/9884652/4a20e0ba-5bb7-11e5-8fa6-43a4062ba5ef.gif)

**Comment by petobens** [comment]
I also have a similar (although not identical) problem when dealing with `R` files. 

Suppose I have the following `R` files in the same directory (this is not strictly necessary):

i) `bar.R`:

``` R
blah <- function (x) {
    y <- x + 2
    return(y)
}
```

ii) `foo.R`

``` R
source("bar.R")
print(blah(2))
```

(i.e from the file `foo.R` I'm calling a function `blah()` defined in the file `bar.R`).

Now, using universal-ctags If run `!ctags -R *.R` from the file `foo.R`, the following tag file is generated:

```
!_TAG_FILE_FORMAT   2   /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED   1   /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR    Universal Ctags Team    //
!_TAG_PROGRAM_NAME  Universal Ctags /Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL   https://ctags.io/   /official site/
!_TAG_PROGRAM_VERSION   Development //
"bar.R" foo.R   /^source("bar.R")$/;"   s
blah    bar.R   /^blah <- function (x) {$/;"    f
y   bar.R   /^    y <- x + 2$/;"    v
```

which then allows me to place the cursor in `blah(2)` (in `foo.R`) and press `C-]` to jump to the `blah()` function definition in `bar.R`. 

On the other hand if from `foo.R` I run `:NeoIncludeMakeCache` and then `:Unite tag/include` I get a buffer with just one candidate:

```
"bar.R"                    @foo.R                k:s         pat:source("bar.R")
```

which means that no tags are generated for `bar.R`

Ideally what I would like is that neoinclude generates tags for the current file and for all files included with the `source()` function (in this case `bar.R`).

**Comment by Shougo** [comment]
> Ideally what I would like is that neoinclude generates tags for the current file and for all files included with the source() function (in this case bar.R).

OK.  I added R support.

> and I run set path? I get path=.,, which means that the current directory is included (however echo g:neoinclude#_paths returns {} .

To analyze other file, you need 'include' or `g:neoinclude#_patterns`.
But in foo.m, it is not found.  So it is failed.
If you need 'ctags -R' auto generator, you should use auto-ctags.vim plugin.

https://github.com/soramugi/auto-ctags.vim

**Comment by petobens** [comment]
Thank you @Shougo  and thanks for the explanation.
