### ISSUE TITLE
ctags is significantly slowing down completion for large projects

### ISSUE THREAD

**Issue by xiongm** [Shougo/neoinclude.vim#9]
this is more of a feature request/suggestion

i am using neoinclude to perform header file (cpp) path completion, and that's the only thing i really want. i found that ctags is significantly slowing down large cpp file with lots of codes/includes. in my case a file with ~2000 lines of codes will freeze the window for up to 10 seconds. my workaround is to disable ctags

" disable ctags
let g:neoinclude#ctags_command = ""

then everything is fast. since im using vim-gutentags to navigate between declaration/definition and vim-clang to do api completion, I have no problem with using neoinclude w/out ctags support. 

from a new user perspective, it would be nice to have an option to explicitly disable ctags. im new to neocomplete, so it took me a while to figure out the root cause of the slowness and come up with the hack above.

**Comment by Shougo** [comment]
OK.  I added the FAQ.
